/** @type {import('next').NextConfig} */
const nextConfig = {
  async rewrites() {
    return [
      // Text Tools
      { source: '/tools/word-counter', destination: '/tools/text/word-counter' },
      { source: '/tools/character-counter', destination: '/tools/text/character-counter' },
      { source: '/tools/case-converter', destination: '/tools/text/case-converter' },
      { source: '/tools/lorem-ipsum', destination: '/tools/text/lorem-ipsum' },
      { source: '/tools/text-reverser', destination: '/tools/text/text-reverser' },
      { source: '/tools/remove-duplicates', destination: '/tools/text/remove-duplicates' },
      { source: '/tools/line-sorter', destination: '/tools/text/line-sorter' },
      { source: '/tools/find-replace', destination: '/tools/text/find-replace' },
      { source: '/tools/text-diff', destination: '/tools/text/text-diff' },
      { source: '/tools/line-counter', destination: '/tools/text/line-counter' },
      { source: '/tools/slug-generator', destination: '/tools/text/slug-generator' },
      { source: '/tools/text-splitter', destination: '/tools/text/text-splitter' },
      { source: '/tools/text-merger', destination: '/tools/text/text-merger' },
      { source: '/tools/whitespace-remover', destination: '/tools/text/whitespace-remover' },
      { source: '/tools/text-repeater', destination: '/tools/text/text-repeater' },
      { source: '/tools/random-text', destination: '/tools/text/random-text' },
      { source: '/tools/text-encoder', destination: '/tools/text/text-encoder' },
      { source: '/tools/text-decoder', destination: '/tools/text/text-decoder' },
      { source: '/tools/text-formatter', destination: '/tools/text/text-formatter' },
      { source: '/tools/text-statistics', destination: '/tools/text/text-statistics' },
      { source: '/tools/readability-score', destination: '/tools/text/readability-score' },
      { source: '/tools/keyword-density', destination: '/tools/text/keyword-density' },
      { source: '/tools/palindrome-checker', destination: '/tools/text/palindrome-checker' },
      { source: '/tools/anagram-solver', destination: '/tools/text/anagram-solver' },
      { source: '/tools/text-to-ascii', destination: '/tools/text/text-to-ascii' },
      { source: '/tools/ascii-art', destination: '/tools/text/ascii-art' },
      { source: '/tools/number-to-words', destination: '/tools/text/number-to-words' },
      { source: '/tools/words-to-number', destination: '/tools/text/words-to-number' },
      { source: '/tools/text-to-speech', destination: '/tools/text/text-to-speech' },
      { source: '/tools/speech-to-text', destination: '/tools/text/speech-to-text' },

      // Calculators
      { source: '/tools/bmi-calculator', destination: '/tools/calculators/bmi-calculator' },
      { source: '/tools/loan-calculator', destination: '/tools/calculators/loan-calculator' },
      { source: '/tools/percentage-calculator', destination: '/tools/calculators/percentage-calculator' },
      { source: '/tools/tip-calculator', destination: '/tools/calculators/tip-calculator' },
      { source: '/tools/discount-calculator', destination: '/tools/calculators/discount-calculator' },
      { source: '/tools/tax-calculator', destination: '/tools/calculators/tax-calculator' },
      { source: '/tools/mortgage-calculator', destination: '/tools/calculators/mortgage-calculator' },
      { source: '/tools/compound-interest', destination: '/tools/calculators/compound-interest' },
      { source: '/tools/simple-interest', destination: '/tools/calculators/simple-interest' },
      { source: '/tools/investment-calculator', destination: '/tools/calculators/investment-calculator' },
      { source: '/tools/retirement-calculator', destination: '/tools/calculators/retirement-calculator' },
      { source: '/tools/salary-calculator', destination: '/tools/calculators/salary-calculator' },
      { source: '/tools/gpa-calculator', destination: '/tools/calculators/gpa-calculator' },
      { source: '/tools/grade-calculator', destination: '/tools/calculators/grade-calculator' },
      { source: '/tools/calorie-calculator', destination: '/tools/calculators/calorie-calculator' },
      { source: '/tools/body-fat-calculator', destination: '/tools/calculators/body-fat-calculator' },
      { source: '/tools/water-intake', destination: '/tools/calculators/water-intake' },
      { source: '/tools/pregnancy-calculator', destination: '/tools/calculators/pregnancy-calculator' },
      { source: '/tools/age-calculator', destination: '/tools/calculators/age-calculator' },
      { source: '/tools/date-calculator', destination: '/tools/calculators/date-calculator' },
      { source: '/tools/time-calculator', destination: '/tools/calculators/time-calculator' },
      { source: '/tools/scientific-calculator', destination: '/tools/calculators/scientific-calculator' },
      { source: '/tools/fraction-calculator', destination: '/tools/calculators/fraction-calculator' },
      { source: '/tools/ratio-calculator', destination: '/tools/calculators/ratio-calculator' },
      { source: '/tools/random-number', destination: '/tools/calculators/random-number' },
      { source: '/tools/probability-calculator', destination: '/tools/calculators/probability-calculator' },
      { source: '/tools/statistics-calculator', destination: '/tools/calculators/statistics-calculator' },
      { source: '/tools/area-calculator', destination: '/tools/calculators/area-calculator' },
      { source: '/tools/volume-calculator', destination: '/tools/calculators/volume-calculator' },
      { source: '/tools/currency-calculator', destination: '/tools/calculators/currency-calculator' },

      // Developer Tools
      { source: '/tools/json-formatter', destination: '/tools/developer/json-formatter' },
      { source: '/tools/json-minifier', destination: '/tools/developer/json-minifier' },
      { source: '/tools/json-validator', destination: '/tools/developer/json-validator' },
      { source: '/tools/json-to-csv', destination: '/tools/developer/json-to-csv' },
      { source: '/tools/csv-to-json', destination: '/tools/developer/csv-to-json' },
      { source: '/tools/json-to-xml', destination: '/tools/developer/json-to-xml' },
      { source: '/tools/xml-to-json', destination: '/tools/developer/xml-to-json' },
      { source: '/tools/json-to-yaml', destination: '/tools/developer/json-to-yaml' },
      { source: '/tools/yaml-to-json', destination: '/tools/developer/yaml-to-json' },
      { source: '/tools/html-beautifier', destination: '/tools/developer/html-beautifier' },
      { source: '/tools/css-beautifier', destination: '/tools/developer/css-beautifier' },
      { source: '/tools/css-minifier', destination: '/tools/developer/css-minifier' },
      { source: '/tools/js-beautifier', destination: '/tools/developer/js-beautifier' },
      { source: '/tools/sql-formatter', destination: '/tools/developer/sql-formatter' },
      { source: '/tools/xml-formatter', destination: '/tools/developer/xml-formatter' },
      { source: '/tools/url-encoder', destination: '/tools/developer/url-encoder' },
      { source: '/tools/url-decoder', destination: '/tools/developer/url-decoder' },
      { source: '/tools/base64-encoder', destination: '/tools/developer/base64-encoder' },
      { source: '/tools/base64-decoder', destination: '/tools/developer/base64-decoder' },
      { source: '/tools/html-entities-encoder', destination: '/tools/developer/html-entities-encoder' },
      { source: '/tools/html-entities-decoder', destination: '/tools/developer/html-entities-decoder' },
      { source: '/tools/regex-tester', destination: '/tools/developer/regex-tester' },
      { source: '/tools/jwt-decoder', destination: '/tools/developer/jwt-decoder' },
      { source: '/tools/html-preview', destination: '/tools/developer/html-preview' },
      { source: '/tools/markdown-preview', destination: '/tools/developer/markdown-preview' },
      { source: '/tools/color-picker', destination: '/tools/developer/color-picker' },
      { source: '/tools/color-converter', destination: '/tools/developer/color-converter' },
      { source: '/tools/gradient-generator', destination: '/tools/developer/gradient-generator' },
      { source: '/tools/color-palette', destination: '/tools/developer/color-palette' },
      { source: '/tools/contrast-checker', destination: '/tools/developer/contrast-checker' },
      { source: '/tools/html-table-generator', destination: '/tools/developer/html-table-generator' },
      { source: '/tools/uuid-generator-dev', destination: '/tools/developer/uuid-generator' },
      { source: '/tools/hash-generator', destination: '/tools/developer/hash-generator' },
      { source: '/tools/cron-generator', destination: '/tools/developer/cron-generator' },
      { source: '/tools/http-status-codes', destination: '/tools/developer/http-status-codes' },

      // Converters
      { source: '/tools/length-converter', destination: '/tools/converters/length-converter' },
      { source: '/tools/weight-converter', destination: '/tools/converters/weight-converter' },
      { source: '/tools/temperature-converter', destination: '/tools/converters/temperature-converter' },
      { source: '/tools/volume-converter', destination: '/tools/converters/volume-converter' },
      { source: '/tools/area-converter', destination: '/tools/converters/area-converter' },
      { source: '/tools/speed-converter', destination: '/tools/converters/speed-converter' },
      { source: '/tools/time-converter', destination: '/tools/converters/time-converter' },
      { source: '/tools/angle-converter', destination: '/tools/converters/angle-converter' },
      { source: '/tools/pressure-converter', destination: '/tools/converters/pressure-converter' },
      { source: '/tools/energy-converter', destination: '/tools/converters/energy-converter' },
      { source: '/tools/data-storage-converter', destination: '/tools/converters/data-storage-converter' },
      { source: '/tools/power-converter', destination: '/tools/converters/power-converter' },
      { source: '/tools/force-converter', destination: '/tools/converters/force-converter' },
      { source: '/tools/frequency-converter', destination: '/tools/converters/frequency-converter' },
      { source: '/tools/distance-converter', destination: '/tools/converters/distance-converter' },
      { source: '/tools/fuel-economy-converter', destination: '/tools/converters/fuel-economy-converter' },
      { source: '/tools/number-base-converter', destination: '/tools/converters/number-base-converter' },
      { source: '/tools/roman-numeral-converter', destination: '/tools/converters/roman-numeral-converter' },
      { source: '/tools/timezone-converter', destination: '/tools/converters/timezone-converter' },
      { source: '/tools/unix-time-converter', destination: '/tools/converters/unix-time-converter' },
      { source: '/tools/date-format-converter', destination: '/tools/converters/date-format-converter' },
      { source: '/tools/text-to-binary-converter', destination: '/tools/converters/text-to-binary-converter' },
      { source: '/tools/binary-to-text-converter', destination: '/tools/converters/binary-to-text-converter' },
      { source: '/tools/text-to-ascii-converter', destination: '/tools/converters/text-to-ascii-converter' },
      { source: '/tools/ascii-to-text-converter', destination: '/tools/converters/ascii-to-text-converter' },
      { source: '/tools/morse-code-converter', destination: '/tools/converters/morse-code-converter' },
      { source: '/tools/cooking-measurement-converter', destination: '/tools/converters/cooking-measurement-converter' },
      { source: '/tools/shoe-size-converter', destination: '/tools/converters/shoe-size-converter' },
      { source: '/tools/digital-storage-converter', destination: '/tools/converters/digital-storage-converter' },
      { source: '/tools/currency-converter', destination: '/tools/converters/currency-converter' },
      { source: '/tools/number-to-words-converter', destination: '/tools/converters/number-to-words-converter' },

      // Security Tools
      { source: '/tools/password-generator', destination: '/tools/security/password-generator' },
      { source: '/tools/password-strength-checker', destination: '/tools/security/password-strength-checker' },
      { source: '/tools/md5-hash-generator', destination: '/tools/security/md5-hash-generator' },
      { source: '/tools/sha1-hash-generator', destination: '/tools/security/sha1-hash-generator' },
      { source: '/tools/sha256-hash-generator', destination: '/tools/security/sha256-hash-generator' },
      { source: '/tools/sha512-hash-generator', destination: '/tools/security/sha512-hash-generator' },
      { source: '/tools/random-string-generator', destination: '/tools/security/random-string-generator' },
      { source: '/tools/uuid-generator', destination: '/tools/security/uuid-generator' },
      { source: '/tools/pin-generator', destination: '/tools/security/pin-generator' },
      { source: '/tools/passphrase-generator', destination: '/tools/security/passphrase-generator' },
      { source: '/tools/jwt-decoder-sec', destination: '/tools/security/jwt-decoder' },
      { source: '/tools/jwt-generator', destination: '/tools/security/jwt-generator' },
      { source: '/tools/bcrypt-hash-generator', destination: '/tools/security/bcrypt-hash-generator' },
      { source: '/tools/bcrypt-verifier', destination: '/tools/security/bcrypt-verifier' },
      { source: '/tools/hmac-generator', destination: '/tools/security/hmac-generator' },
      { source: '/tools/aes-text-encryptor', destination: '/tools/security/aes-text-encryptor' },
      { source: '/tools/aes-text-decryptor', destination: '/tools/security/aes-text-decryptor' },
      { source: '/tools/random-bytes-generator', destination: '/tools/security/random-bytes-generator' },
      { source: '/tools/hash-comparison-tool', destination: '/tools/security/hash-comparison-tool' },
      { source: '/tools/base64-hex-converter', destination: '/tools/security/base64-hex-converter' },

      // QR & Barcode Tools
      { source: '/tools/qr-code-generator', destination: '/tools/qr-barcode/qr-code-generator' },
      { source: '/tools/wifi-qr-generator', destination: '/tools/qr-barcode/wifi-qr-generator' },
      { source: '/tools/vcard-qr-generator', destination: '/tools/qr-barcode/vcard-qr-generator' },
      { source: '/tools/email-qr-generator', destination: '/tools/qr-barcode/email-qr-generator' },
      { source: '/tools/sms-qr-generator', destination: '/tools/qr-barcode/sms-qr-generator' },
      { source: '/tools/phone-qr-generator', destination: '/tools/qr-barcode/phone-qr-generator' },
      { source: '/tools/location-qr-generator', destination: '/tools/qr-barcode/location-qr-generator' },
      { source: '/tools/event-qr-generator', destination: '/tools/qr-barcode/event-qr-generator' },
      { source: '/tools/bulk-qr-generator', destination: '/tools/qr-barcode/bulk-qr-generator' },
      { source: '/tools/qr-code-reader', destination: '/tools/qr-barcode/qr-code-reader' },
      { source: '/tools/code128-barcode-generator', destination: '/tools/qr-barcode/code128-barcode-generator' },
      { source: '/tools/ean13-barcode-generator', destination: '/tools/qr-barcode/ean13-barcode-generator' },
      { source: '/tools/upca-barcode-generator', destination: '/tools/qr-barcode/upca-barcode-generator' },
      { source: '/tools/code39-barcode-generator', destination: '/tools/qr-barcode/code39-barcode-generator' },
      { source: '/tools/barcode-reader', destination: '/tools/qr-barcode/barcode-reader' },

      // Image Tools
      { source: '/tools/image-compressor', destination: '/tools/image/image-compressor' },
      { source: '/tools/image-resizer', destination: '/tools/image/image-resizer' },
      { source: '/tools/image-cropper', destination: '/tools/image/image-cropper' },
      { source: '/tools/image-rotator', destination: '/tools/image/image-rotator' },
      { source: '/tools/image-flipper', destination: '/tools/image/image-flipper' },
      { source: '/tools/image-converter', destination: '/tools/image/image-converter' },
      { source: '/tools/image-to-base64', destination: '/tools/image/image-to-base64' },
      { source: '/tools/base64-to-image', destination: '/tools/image/base64-to-image' },
      { source: '/tools/favicon-generator', destination: '/tools/image/favicon-generator' },
      { source: '/tools/image-color-picker', destination: '/tools/image/image-color-picker' },
      { source: '/tools/image-watermark', destination: '/tools/image/image-watermark' },
      { source: '/tools/image-filter', destination: '/tools/image/image-filter' },
      { source: '/tools/image-brightness-contrast', destination: '/tools/image/image-brightness-contrast' },
      { source: '/tools/png-to-jpg', destination: '/tools/image/png-to-jpg' },
      { source: '/tools/jpg-to-png', destination: '/tools/image/jpg-to-png' },
      { source: '/tools/png-to-webp', destination: '/tools/image/png-to-webp' },
      { source: '/tools/webp-to-png', destination: '/tools/image/webp-to-png' },
      { source: '/tools/image-border', destination: '/tools/image/image-border' },
      { source: '/tools/image-exif-viewer', destination: '/tools/image/image-exif-viewer' },
      { source: '/tools/image-placeholder-generator', destination: '/tools/image/image-placeholder-generator' },
      { source: '/tools/image-blur-tool', destination: '/tools/image/image-blur-tool' },
      { source: '/tools/svg-to-png-converter', destination: '/tools/image/svg-to-png-converter' },
      { source: '/tools/image-merger', destination: '/tools/image/image-merger' },
      { source: '/tools/image-splitter', destination: '/tools/image/image-splitter' },
      { source: '/tools/bulk-image-compressor', destination: '/tools/image/bulk-image-compressor' },

      // PDF Tools
      { source: '/tools/pdf-merger', destination: '/tools/pdf/pdf-merger' },
      { source: '/tools/pdf-splitter', destination: '/tools/pdf/pdf-splitter' },
      { source: '/tools/pdf-compressor', destination: '/tools/pdf/pdf-compressor' },
      { source: '/tools/pdf-rotator', destination: '/tools/pdf/pdf-rotator' },
      { source: '/tools/pdf-to-image', destination: '/tools/pdf/pdf-to-image' },
      { source: '/tools/image-to-pdf', destination: '/tools/pdf/image-to-pdf' },
      { source: '/tools/pdf-password-protector', destination: '/tools/pdf/pdf-password-protector' },
      { source: '/tools/pdf-watermark', destination: '/tools/pdf/pdf-watermark' },
      { source: '/tools/pdf-page-extractor', destination: '/tools/pdf/pdf-page-extractor' },
      { source: '/tools/pdf-to-text', destination: '/tools/pdf/pdf-to-text' },
      { source: '/tools/pdf-page-deleter', destination: '/tools/pdf/pdf-page-deleter' },
      { source: '/tools/pdf-page-reorder', destination: '/tools/pdf/pdf-page-reorder' },
      { source: '/tools/pdf-metadata-editor', destination: '/tools/pdf/pdf-metadata-editor' },
      { source: '/tools/pdf-page-counter', destination: '/tools/pdf/pdf-page-counter' },
      { source: '/tools/pdf-password-remover', destination: '/tools/pdf/pdf-password-remover' },
    ]
  },
}

module.exports = nextConfig