// src/config/prompts-data.ts
export type AIModel = 'ChatGPT' | 'Midjourney' | 'DALL-E' | 'Stable Diffusion' | 'Claude' | 'Gemini' | 'GitHub Copilot' | 'Runway' | 'Suno' | 'ElevenLabs' | 'Pika'

export interface Prompt {
  id: string
  slug: string
  title: string
  description: string
  category: string
  prompt: string
  aiModel: AIModel
  tags: string[]
  isPopular: boolean
  isFeatured: boolean
  isPremium: boolean
  views: number
  emoji: string
  gradient: string
  imageUrl: string
  imageKeyword: string
}

export interface PromptCategory {
  slug: string
  name: string
  description: string
  icon: string
  gradient: string
  count: number
}

export const promptCategories: PromptCategory[] = [
  { slug: 'chatgpt', name: 'ChatGPT', description: 'Writing, business, marketing prompts', icon: '🤖', gradient: 'from-green-500 to-emerald-600', count: 5 },
  { slug: 'midjourney', name: 'Midjourney', description: 'Stunning AI art prompts', icon: '🎨', gradient: 'from-purple-500 to-pink-600', count: 5 },
  { slug: 'dalle', name: 'DALL-E', description: 'Creative image generation', icon: '🖼️', gradient: 'from-blue-500 to-cyan-600', count: 3 },
  { slug: 'stable-diffusion', name: 'Stable Diffusion', description: 'Advanced image prompts', icon: '✨', gradient: 'from-orange-500 to-red-600', count: 2 },
  { slug: 'claude', name: 'Claude', description: 'Analysis and research prompts', icon: '🧠', gradient: 'from-amber-500 to-yellow-600', count: 3 },
  { slug: 'gemini', name: 'Gemini', description: 'Multimodal AI prompts', icon: '💎', gradient: 'from-cyan-500 to-blue-600', count: 2 },
  { slug: 'coding', name: 'AI Coding', description: 'Code, debug, review prompts', icon: '💻', gradient: 'from-green-500 to-teal-600', count: 2 },
  { slug: 'video', name: 'Video AI', description: 'Runway, Pika prompts', icon: '🎬', gradient: 'from-red-500 to-pink-600', count: 2 },
  { slug: 'music', name: 'Music AI', description: 'Suno, Udio music prompts', icon: '🎵', gradient: 'from-pink-500 to-rose-600', count: 2 },
  { slug: 'voice', name: 'Voice AI', description: 'ElevenLabs voice prompts', icon: '🎙️', gradient: 'from-violet-500 to-purple-600', count: 2 },
]

export const allPrompts: Prompt[] = [
  { id: 'cg-001', slug: 'professional-email-writer', title: 'Professional Email Writer', description: 'Perfect professional emails for any situation', category: 'chatgpt', prompt: 'You are a professional email writing expert. Write a professional email based on the following details:\n\nPurpose: [EMAIL PURPOSE]\nRecipient: [WHO YOU ARE WRITING TO]\nTone: [FORMAL/SEMI-FORMAL/FRIENDLY]', aiModel: 'ChatGPT', tags: ['email','writing','professional','business'], isPopular: true, isFeatured: true, isPremium: false, views: 15420, emoji: '📧', gradient: 'from-green-500 via-emerald-600 to-teal-700', imageUrl: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=400&h=500&fit=crop&q=80', imageKeyword: 'business email laptop' },
  { id: 'cg-002', slug: 'blog-post-outline-generator', title: 'Blog Post Outline Generator', description: 'SEO-friendly blog post outlines in minutes', category: 'chatgpt', prompt: 'Act as an expert content strategist and SEO specialist. Create a comprehensive blog post outline for:\n\nTopic: [YOUR BLOG TOPIC]\nTarget Keyword: [MAIN SEO KEYWORD]', aiModel: 'ChatGPT', tags: ['blog','SEO','content','writing'], isPopular: true, isFeatured: true, isPremium: false, views: 12350, emoji: '📝', gradient: 'from-blue-600 via-cyan-500 to-teal-500', imageUrl: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=400&h=500&fit=crop&q=80', imageKeyword: 'blog writing notebook' },
  { id: 'cg-003', slug: 'business-plan-creator', title: 'Startup Business Plan Creator', description: 'Investor-ready business plans instantly', category: 'chatgpt', prompt: 'You are a seasoned business consultant. Create a comprehensive business plan for:\n\nBusiness Name: [YOUR BUSINESS NAME]\nIndustry: [YOUR INDUSTRY]', aiModel: 'ChatGPT', tags: ['business','startup','plan','entrepreneur'], isPopular: true, isFeatured: false, isPremium: true, views: 9870, emoji: '💼', gradient: 'from-indigo-600 via-purple-600 to-pink-500', imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&h=500&fit=crop&q=80', imageKeyword: 'business meeting startup' },
  { id: 'cg-004', slug: 'social-media-content-calendar', title: '30-Day Social Media Calendar', description: 'Complete content calendar for any platform', category: 'chatgpt', prompt: 'You are a social media marketing expert. Create a 30-day content calendar for:\n\nBrand: [YOUR BRAND]\nPlatforms: [INSTAGRAM/TWITTER/LINKEDIN]', aiModel: 'ChatGPT', tags: ['social media','marketing','content','instagram'], isPopular: true, isFeatured: true, isPremium: false, views: 18900, emoji: '📱', gradient: 'from-rose-500 via-pink-600 to-purple-700', imageUrl: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=400&h=500&fit=crop&q=80', imageKeyword: 'social media phone instagram' },
  { id: 'cg-005', slug: 'resume-optimizer', title: 'ATS Resume Optimizer', description: 'Make your resume ATS-friendly instantly', category: 'chatgpt', prompt: 'You are an expert resume writer. Optimize my resume for ATS systems.\n\nJob Title: [TARGET JOB]\nExperience: [X YEARS]', aiModel: 'ChatGPT', tags: ['resume','job','ATS','career'], isPopular: true, isFeatured: true, isPremium: false, views: 22100, emoji: '📄', gradient: 'from-emerald-500 via-teal-600 to-cyan-700', imageUrl: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=400&h=500&fit=crop&q=80', imageKeyword: 'resume job interview' },
  { id: 'mj-001', slug: 'cinematic-portrait-prompt', title: 'Cinematic Portrait Photography', description: 'Hollywood-level cinematic portraits', category: 'midjourney', prompt: 'cinematic portrait of [SUBJECT], golden hour lighting, shot on ARRI Alexa, 85mm lens, shallow depth of field, bokeh background --ar 2:3 --v 6', aiModel: 'Midjourney', tags: ['portrait','cinematic','photography','film'], isPopular: true, isFeatured: true, isPremium: false, views: 28900, emoji: '📸', gradient: 'from-purple-600 via-pink-600 to-red-600', imageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=500&fit=crop&q=80', imageKeyword: 'cinematic portrait woman' },
  { id: 'mj-002', slug: 'fantasy-landscape-prompt', title: 'Epic Fantasy Landscape', description: 'LOTR-style fantasy landscape art', category: 'midjourney', prompt: 'epic fantasy landscape, [SCENE], dramatic volumetric lighting, mystical fog, magical atmosphere, matte painting style --ar 16:9 --v 6', aiModel: 'Midjourney', tags: ['fantasy','landscape','epic','art'], isPopular: true, isFeatured: true, isPremium: true, views: 24500, emoji: '🏰', gradient: 'from-indigo-600 via-purple-600 to-pink-500', imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&h=500&fit=crop&q=80', imageKeyword: 'fantasy mountain landscape' },
  { id: 'mj-003', slug: 'product-photography-prompt', title: 'Luxury Product Photography', description: 'Brand-level product photography', category: 'midjourney', prompt: 'luxury product photography, [PRODUCT], studio lighting, hero shot, rim lighting, ultra detailed --ar 1:1 --v 6', aiModel: 'Midjourney', tags: ['product','photography','commercial'], isPopular: true, isFeatured: false, isPremium: false, views: 19800, emoji: '💎', gradient: 'from-yellow-500 via-orange-500 to-red-600', imageUrl: 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=400&h=500&fit=crop&q=80', imageKeyword: 'luxury perfume product' },
  { id: 'mj-004', slug: 'cyberpunk-city-prompt', title: 'Cyberpunk City Nightscape', description: 'Blade Runner inspired cyberpunk art', category: 'midjourney', prompt: 'cyberpunk megacity at night, neon signs, flying vehicles, holographic ads, blade runner 2049 aesthetic --ar 16:9 --v 6', aiModel: 'Midjourney', tags: ['cyberpunk','city','neon','sci-fi'], isPopular: true, isFeatured: true, isPremium: false, views: 31200, emoji: '🌆', gradient: 'from-cyan-500 via-blue-600 to-indigo-700', imageUrl: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=400&h=500&fit=crop&q=80', imageKeyword: 'cyberpunk neon city night' },
  { id: 'mj-005', slug: 'anime-character-design', title: 'Anime Character Design', description: 'Professional anime character sheets', category: 'midjourney', prompt: 'anime character design sheet, [CHARACTER], multiple poses, expression sheet, Studio Ghibli style --ar 1:1 --v 6 --niji 6', aiModel: 'Midjourney', tags: ['anime','character','design','manga'], isPopular: true, isFeatured: false, isPremium: false, views: 27600, emoji: '🎌', gradient: 'from-pink-500 via-purple-500 to-indigo-600', imageUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=400&h=500&fit=crop&q=80', imageKeyword: 'anime character japanese' },
  { id: 'de-001', slug: 'minimalist-logo-dalle', title: 'Minimalist Logo Design', description: 'Clean professional logos instantly', category: 'dalle', prompt: 'Create a minimalist professional logo for [BUSINESS TYPE]. Simple geometric design, flat design, professional corporate look.', aiModel: 'DALL-E', tags: ['logo','minimalist','branding'], isPopular: true, isFeatured: true, isPremium: false, views: 21000, emoji: '🎯', gradient: 'from-blue-600 via-cyan-500 to-teal-500', imageUrl: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=400&h=500&fit=crop&q=80', imageKeyword: 'minimalist logo design' },
  { id: 'de-002', slug: 'youtube-thumbnail-dalle', title: 'YouTube Thumbnail Design', description: 'High CTR thumbnails that get clicks', category: 'dalle', prompt: 'Create a high-impact YouTube thumbnail for [VIDEO TOPIC]. Bold eye-catching background, contrasting colors, 16:9 ratio.', aiModel: 'DALL-E', tags: ['youtube','thumbnail','CTR','video'], isPopular: true, isFeatured: true, isPremium: false, views: 24600, emoji: '🎥', gradient: 'from-red-500 via-orange-500 to-yellow-500', imageUrl: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=400&h=500&fit=crop&q=80', imageKeyword: 'youtube video creator' },
  { id: 'de-003', slug: 'brand-mascot-dalle', title: 'Brand Mascot Character', description: 'Memorable mascot for your brand', category: 'dalle', prompt: 'Create a friendly brand mascot for [BRAND NAME]. Cartoon character, friendly and approachable, front-facing pose.', aiModel: 'DALL-E', tags: ['mascot','character','branding'], isPopular: true, isFeatured: false, isPremium: false, views: 18200, emoji: '🎭', gradient: 'from-orange-500 via-red-500 to-pink-600', imageUrl: 'https://images.unsplash.com/photo-1618172193763-c511deb635ca?w=400&h=500&fit=crop&q=80', imageKeyword: 'cute cartoon mascot' },
  { id: 'sd-001', slug: 'photorealistic-portrait-sd', title: 'Photorealistic Portrait', description: 'Ultra-realistic human portraits', category: 'stable-diffusion', prompt: 'photorealistic portrait photo of [DESCRIPTION], Canon EOS R5, 85mm f/1.4, natural lighting, 8K, hyperrealistic', aiModel: 'Stable Diffusion', tags: ['portrait','photorealistic','photography'], isPopular: true, isFeatured: true, isPremium: false, views: 32000, emoji: '👤', gradient: 'from-amber-500 via-orange-600 to-red-700', imageUrl: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=500&fit=crop&q=80', imageKeyword: 'photorealistic man portrait' },
  { id: 'sd-002', slug: 'anime-landscape-sd', title: 'Ghibli Anime Landscape', description: 'Studio Ghibli style landscapes', category: 'stable-diffusion', prompt: 'anime landscape, [SCENE], studio ghibli style, Hayao Miyazaki inspired, watercolor aesthetic, soft colors', aiModel: 'Stable Diffusion', tags: ['anime','landscape','ghibli'], isPopular: true, isFeatured: false, isPremium: false, views: 28500, emoji: '🌸', gradient: 'from-pink-500 via-rose-500 to-purple-600', imageUrl: 'https://images.unsplash.com/photo-1522383225653-ed111181a951?w=400&h=500&fit=crop&q=80', imageKeyword: 'cherry blossom landscape' },
  { id: 'cl-001', slug: 'code-reviewer-claude', title: 'Expert Code Reviewer', description: 'Professional code review with fixes', category: 'claude', prompt: 'You are a senior software engineer. Review this code:\n\nLanguage: [LANGUAGE]\nCode:\n[PASTE CODE]', aiModel: 'Claude', tags: ['code','review','programming'], isPopular: true, isFeatured: true, isPremium: false, views: 19400, emoji: '🔍', gradient: 'from-emerald-500 via-teal-600 to-cyan-700', imageUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400&h=500&fit=crop&q=80', imageKeyword: 'code programming laptop' },
  { id: 'cl-002', slug: 'legal-document-analyzer', title: 'Legal Document Explainer', description: 'Complex legal docs in plain English', category: 'claude', prompt: 'You are a legal expert. Analyze this legal document:\n\n[PASTE DOCUMENT]', aiModel: 'Claude', tags: ['legal','contract','analysis'], isPopular: true, isFeatured: true, isPremium: true, views: 24500, emoji: '⚖️', gradient: 'from-amber-500 via-yellow-600 to-orange-700', imageUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=400&h=500&fit=crop&q=80', imageKeyword: 'legal document contract' },
  { id: 'cl-003', slug: 'brainstorming-facilitator', title: 'Creative Brainstorming', description: '100+ creative ideas for any problem', category: 'claude', prompt: 'You are a creative facilitator. Brainstorm solutions for:\n\nProblem: [YOUR CHALLENGE]', aiModel: 'Claude', tags: ['brainstorming','creativity','ideas'], isPopular: true, isFeatured: false, isPremium: false, views: 14500, emoji: '💡', gradient: 'from-purple-500 via-indigo-500 to-blue-600', imageUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=500&fit=crop&q=80', imageKeyword: 'brainstorming team creative' },
  { id: 'cd-001', slug: 'react-component-builder', title: 'React Component Builder', description: 'Production-ready React components', category: 'coding', prompt: 'You are a senior React developer. Build a production-ready component:\n\nComponent: [NAME]', aiModel: 'GitHub Copilot', tags: ['React','Next.js','TypeScript'], isPopular: true, isFeatured: true, isPremium: false, views: 26800, emoji: '⚛️', gradient: 'from-cyan-500 via-blue-500 to-indigo-600', imageUrl: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=400&h=500&fit=crop&q=80', imageKeyword: 'react javascript code' },
  { id: 'cd-002', slug: 'bug-fixer-debugger', title: 'Expert Bug Fixer', description: 'Fix stubborn bugs instantly', category: 'coding', prompt: 'You are an expert debugger. Fix this bug:\n\nLanguage: [LANG]\nCode:\n[PASTE CODE]', aiModel: 'GitHub Copilot', tags: ['debugging','bug fix','error'], isPopular: true, isFeatured: false, isPremium: false, views: 31200, emoji: '🐛', gradient: 'from-red-500 via-orange-500 to-yellow-600', imageUrl: 'https://images.unsplash.com/photo-1580927752452-89d86da3fa0a?w=400&h=500&fit=crop&q=80', imageKeyword: 'coding debug programming' },
  { id: 'vi-001', slug: 'cinematic-drone-shot', title: 'Cinematic Drone Shot', description: 'Hollywood-level aerial footage', category: 'video', prompt: 'Cinematic drone shot, [LOCATION], slow sweeping movement, golden hour, 4K quality, film grain', aiModel: 'Runway', tags: ['drone','cinematic','video'], isPopular: true, isFeatured: true, isPremium: false, views: 24500, emoji: '🚁', gradient: 'from-blue-600 via-purple-600 to-pink-600', imageUrl: 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=400&h=500&fit=crop&q=80', imageKeyword: 'drone aerial mountain' },
  { id: 'vi-002', slug: 'social-media-short-video', title: 'Viral Short Video', description: 'Instagram/TikTok viral content', category: 'video', prompt: 'Social media short video, [CONCEPT], 9:16 format, trendy style, 5-10 seconds', aiModel: 'Pika', tags: ['social media','TikTok','viral'], isPopular: true, isFeatured: false, isPremium: false, views: 28900, emoji: '📲', gradient: 'from-pink-500 via-purple-500 to-indigo-600', imageUrl: 'https://images.unsplash.com/photo-1516251193007-45ef944ab0c6?w=400&h=500&fit=crop&q=80', imageKeyword: 'tiktok phone video' },
  { id: 'mu-001', slug: 'epic-cinematic-music', title: 'Epic Cinematic Score', description: 'Hollywood movie trailer music', category: 'music', prompt: 'Epic cinematic orchestral score, [MOOD], full orchestra with choir, Hans Zimmer style', aiModel: 'Suno', tags: ['cinematic','orchestral','film score'], isPopular: true, isFeatured: true, isPremium: false, views: 19800, emoji: '🎼', gradient: 'from-purple-600 via-pink-500 to-red-500', imageUrl: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=400&h=500&fit=crop&q=80', imageKeyword: 'orchestra classical music' },
  { id: 'mu-002', slug: 'lofi-hip-hop-track', title: 'Lo-Fi Study Music', description: 'Chill beats for studying', category: 'music', prompt: 'Chill lo-fi hip hop track, relaxing study music, jazz piano, soft drums, 70-90 BPM', aiModel: 'Suno', tags: ['lo-fi','hip hop','study','chill'], isPopular: true, isFeatured: false, isPremium: false, views: 31200, emoji: '🎧', gradient: 'from-indigo-600 via-blue-600 to-cyan-500', imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=500&fit=crop&q=80', imageKeyword: 'lofi headphones vinyl' },
  { id: 'gm-001', slug: 'youtube-video-summarizer', title: 'YouTube Video Summarizer', description: 'Long videos into key notes', category: 'gemini', prompt: '[PASTE YOUTUBE URL]\n\nCreate comprehensive notes with key points, timestamps, takeaways', aiModel: 'Gemini', tags: ['youtube','summary','notes'], isPopular: true, isFeatured: true, isPremium: false, views: 23400, emoji: '▶️', gradient: 'from-red-500 via-pink-500 to-purple-600', imageUrl: 'https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=400&h=500&fit=crop&q=80', imageKeyword: 'youtube video notes' },
  { id: 'gm-002', slug: 'travel-planner-gemini', title: 'AI Travel Planner', description: 'Complete personalized itineraries', category: 'gemini', prompt: 'Plan my trip:\n\nDestination: [WHERE]\nDuration: [DAYS]\nBudget: [AMOUNT]', aiModel: 'Gemini', tags: ['travel','itinerary','vacation'], isPopular: true, isFeatured: true, isPremium: true, views: 28700, emoji: '✈️', gradient: 'from-cyan-500 via-blue-500 to-indigo-600', imageUrl: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=400&h=500&fit=crop&q=80', imageKeyword: 'travel map airplane' },
  { id: 'vo-001', slug: 'audiobook-narrator-prompt', title: 'Audiobook Narrator Voice', description: 'Professional narration settings', category: 'voice', prompt: 'ElevenLabs Voice Settings:\nVoice: [WARM DEEP]\nStability: 0.75\nStyle: 0.3', aiModel: 'ElevenLabs', tags: ['audiobook','narration','voice'], isPopular: true, isFeatured: true, isPremium: false, views: 18400, emoji: '📖', gradient: 'from-violet-500 via-purple-600 to-indigo-700', imageUrl: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=400&h=500&fit=crop&q=80', imageKeyword: 'audiobook headphones' },
  { id: 'vo-002', slug: 'youtube-video-voice', title: 'YouTube Creator Voice', description: 'Engaging voice for content', category: 'voice', prompt: 'ElevenLabs YouTube Voice:\nEnergy: HIGH\nStability: 0.60\nSpeed: 1.05', aiModel: 'ElevenLabs', tags: ['YouTube','voice over','content'], isPopular: true, isFeatured: false, isPremium: false, views: 21400, emoji: '🎤', gradient: 'from-orange-500 via-red-500 to-pink-600', imageUrl: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=400&h=500&fit=crop&q=80', imageKeyword: 'microphone podcast' },
]

export function getPopularPrompts(limit: number = 12): Prompt[] {
  return [...allPrompts].sort((a, b) => b.views - a.views).slice(0, limit)
}
export function getFeaturedPrompts(limit: number = 6): Prompt[] {
  return allPrompts.filter(p => p.isFeatured).slice(0, limit)
}
export function getLatestPrompts(limit: number = 12): Prompt[] {
  return [...allPrompts].reverse().slice(0, limit)
}
export function getPremiumPrompts(limit: number = 6): Prompt[] {
  return allPrompts.filter(p => p.isPremium).slice(0, limit)
}
export function getTrendingPrompts(limit: number = 6): Prompt[] {
  return [...allPrompts].sort((a, b) => b.views - a.views).slice(0, limit)
}
export function getPromptsByCategory(categorySlug: string): Prompt[] {
  return allPrompts.filter(p => p.category === categorySlug)
}

export const totalPrompts = allPrompts.length